// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjetSessionBackend.Core.Models.Entities;

#nullable disable

namespace ProjetSessionBackend.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240427033316_AddCreateAndUpdateTimeToTables")]
    partial class AddCreateAndUpdateTimeToTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjetSessionBackend.Core.Models.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2024, 4, 27, 3, 33, 15, 442, DateTimeKind.Utc).AddTicks(3010),
                            Name = "Admin",
                            UpdatedAt = new DateTime(2024, 4, 27, 3, 33, 15, 442, DateTimeKind.Utc).AddTicks(3010)
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2024, 4, 27, 3, 33, 15, 442, DateTimeKind.Utc).AddTicks(3010),
                            Name = "Employee",
                            UpdatedAt = new DateTime(2024, 4, 27, 3, 33, 15, 442, DateTimeKind.Utc).AddTicks(3010)
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2024, 4, 27, 3, 33, 15, 442, DateTimeKind.Utc).AddTicks(3010),
                            Name = "Client",
                            UpdatedAt = new DateTime(2024, 4, 27, 3, 33, 15, 442, DateTimeKind.Utc).AddTicks(3010)
                        });
                });

            modelBuilder.Entity("ProjetSessionBackend.Core.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2024, 4, 27, 3, 33, 15, 442, DateTimeKind.Utc).AddTicks(3010),
                            Email = "admin@outlook.com",
                            Firstname = "Admin",
                            Lastname = "Admin",
                            Password = "$2a$12$zUuir73jpUqq8st.QM2EJ.WdnWd9RpOk1D/hFewroZ7cyx89jCkma",
                            Phone = "1234567890",
                            RoleId = 1,
                            UpdatedAt = new DateTime(2024, 4, 27, 3, 33, 15, 442, DateTimeKind.Utc).AddTicks(3010)
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2024, 4, 27, 3, 33, 15, 442, DateTimeKind.Utc).AddTicks(3010),
                            Email = "bob.dole@outlook.com",
                            Firstname = "Bob",
                            Lastname = "Dole",
                            Password = "$2a$12$0fiuVeYMB7KDEEsR9n7EieKkN7ntIa3pWbai29JRJpc15SwqDLlYm",
                            Phone = "1234567890",
                            RoleId = 2,
                            UpdatedAt = new DateTime(2024, 4, 27, 3, 33, 15, 442, DateTimeKind.Utc).AddTicks(3010)
                        });
                });

            modelBuilder.Entity("ProjetSessionBackend.Core.Models.Entities.User", b =>
                {
                    b.HasOne("ProjetSessionBackend.Core.Models.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
