// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjetSessionBackend.Core.Models.Entities;

#nullable disable

namespace ProjetSessionBackend.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240428222156_MenuMenuItemTableNameNotPlural")]
    partial class MenuMenuItemTableNameNotPlural
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjetSessionBackend.Core.Models.Entities.ClientBillingInfo", b =>
                {
                    b.Property<int>("ClientBillingInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientBillingInfoId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpiryDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ClientBillingInfoId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ClientBillingInfos");
                });

            modelBuilder.Entity("ProjetSessionBackend.Core.Models.Entities.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MenuId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MenuId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            Name = "Menu classique"
                        },
                        new
                        {
                            MenuId = 2,
                            Name = "Menu santé"
                        },
                        new
                        {
                            MenuId = 3,
                            Name = "Menu végétarien"
                        },
                        new
                        {
                            MenuId = 4,
                            Name = "Menu enfant"
                        });
                });

            modelBuilder.Entity("ProjetSessionBackend.Core.Models.Entities.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MenuItemId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MenuItemId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            Description = "Frites, sauce, fromage",
                            MenuId = 0,
                            Name = "Poutine",
                            Price = 10.99m
                        },
                        new
                        {
                            MenuItemId = 2,
                            Description = "Tomate, fromage, pepperoni",
                            MenuId = 0,
                            Name = "Pizza",
                            Price = 12.99m
                        },
                        new
                        {
                            MenuItemId = 3,
                            Description = "Poulet, frites",
                            MenuId = 0,
                            Name = "Poulet",
                            Price = 15.99m
                        },
                        new
                        {
                            MenuItemId = 4,
                            Description = "Laitue, tomate, concombre",
                            MenuId = 0,
                            Name = "Salade",
                            Price = 8.99m
                        },
                        new
                        {
                            MenuItemId = 5,
                            Description = "Poisson, riz",
                            MenuId = 0,
                            Name = "Poisson",
                            Price = 14.99m
                        },
                        new
                        {
                            MenuItemId = 6,
                            Description = "Pâtes, sauce, fromage",
                            MenuId = 0,
                            Name = "Pâtes",
                            Price = 11.99m
                        });
                });

            modelBuilder.Entity("ProjetSessionBackend.Core.Models.Entities.MenuMenuItem", b =>
                {
                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.HasKey("MenuId", "MenuItemId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("MenuMenuItem");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            MenuItemId = 1
                        },
                        new
                        {
                            MenuId = 1,
                            MenuItemId = 2
                        },
                        new
                        {
                            MenuId = 1,
                            MenuItemId = 3
                        },
                        new
                        {
                            MenuId = 1,
                            MenuItemId = 4
                        },
                        new
                        {
                            MenuId = 1,
                            MenuItemId = 5
                        },
                        new
                        {
                            MenuId = 1,
                            MenuItemId = 6
                        },
                        new
                        {
                            MenuId = 2,
                            MenuItemId = 4
                        },
                        new
                        {
                            MenuId = 2,
                            MenuItemId = 5
                        },
                        new
                        {
                            MenuId = 2,
                            MenuItemId = 6
                        },
                        new
                        {
                            MenuId = 3,
                            MenuItemId = 4
                        },
                        new
                        {
                            MenuId = 3,
                            MenuItemId = 6
                        },
                        new
                        {
                            MenuId = 4,
                            MenuItemId = 4
                        },
                        new
                        {
                            MenuId = 4,
                            MenuItemId = 6
                        });
                });

            modelBuilder.Entity("ProjetSessionBackend.Core.Models.Entities.Restaurant", b =>
                {
                    b.Property<int>("RestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RestaurantId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RestaurantId");

                    b.HasIndex("MenuId");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            RestaurantId = 1,
                            Address = "123 rue de la rue",
                            MenuId = 1,
                            Name = "Sorel-Tracy"
                        },
                        new
                        {
                            RestaurantId = 2,
                            Address = "456 rue de la rue",
                            MenuId = 2,
                            Name = "Montréal"
                        },
                        new
                        {
                            RestaurantId = 3,
                            Address = "789 rue de la rue",
                            MenuId = 3,
                            Name = "Québec"
                        },
                        new
                        {
                            RestaurantId = 4,
                            Address = "1011 rue de la rue",
                            MenuId = 4,
                            Name = "Laval"
                        },
                        new
                        {
                            RestaurantId = 5,
                            Address = "1213 rue de la rue",
                            MenuId = 1,
                            Name = "Longueuil"
                        },
                        new
                        {
                            RestaurantId = 6,
                            Address = "1415 rue de la rue",
                            MenuId = 2,
                            Name = "Sherbrooke"
                        },
                        new
                        {
                            RestaurantId = 7,
                            Address = "1617 rue de la rue",
                            MenuId = 3,
                            Name = "Trois-Rivières"
                        });
                });

            modelBuilder.Entity("ProjetSessionBackend.Core.Models.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Employee"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Client"
                        });
                });

            modelBuilder.Entity("ProjetSessionBackend.Core.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@outlook.com",
                            Firstname = "Admin",
                            Lastname = "Admin",
                            Password = "$2a$12$WGQgHxhjvpA0FrGY8VNyueJzeVEnlARUJBNeIZu7UoqOMLlwykkOO",
                            Phone = "1234567890",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            Email = "bob.dole@outlook.com",
                            Firstname = "Bob",
                            Lastname = "Dole",
                            Password = "$2a$12$ivRdI.W3Kn74fXRaNkal.ea4lU7zyfWsYv3yPxcqMqR3aYJ0vE6Fa",
                            Phone = "1234567890",
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            Email = "john.doe@outlook.com",
                            Firstname = "John",
                            Lastname = "Doe",
                            Password = "$2a$12$LnO8piOQ1/gY9D6Gi4QQs.wOP8lzIS.dpE48agrnufNMTVud/Yrxy",
                            Phone = "1234567890",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("ProjetSessionBackend.Core.Models.Entities.ClientBillingInfo", b =>
                {
                    b.HasOne("ProjetSessionBackend.Core.Models.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("ProjetSessionBackend.Core.Models.Entities.ClientBillingInfo", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjetSessionBackend.Core.Models.Entities.MenuMenuItem", b =>
                {
                    b.HasOne("ProjetSessionBackend.Core.Models.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjetSessionBackend.Core.Models.Entities.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("ProjetSessionBackend.Core.Models.Entities.Restaurant", b =>
                {
                    b.HasOne("ProjetSessionBackend.Core.Models.Entities.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("ProjetSessionBackend.Core.Models.Entities.User", b =>
                {
                    b.HasOne("ProjetSessionBackend.Core.Models.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
